[package]
name = "terraswap"
version = "2.9.0"
authors = ["Terraform Labs, PTE.", "DELIGHT LABS"]
edition = "2018"
description = "Common terraswap types"
license = "Apache-2.0"
repository = "https://github.com/terraswap/terraswap"
homepage = "https://terraswap.io"
documentation = "https://docs.terraswap.io"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib

[dependencies]
cw2 = { version = "2.0.0" }
cw20 = { version = "2.0.0" } 
cosmwasm-std = { version = "2.1.0", features = ["stargate"] }
schemars = "0.8.10"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
protobuf = { version = "2", features = ["with-bytes"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
